### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by pawelsawicz** [mpapierski/openhelbreath#1]
Hey,

What is status of this project ? Is it finished if not then what is missing ?
I got some problems with compiling Client and GameServer, did you manage to compile sources in current state ?

Cheers
Pawel

**Comment by mpapierski** [comment]
I have no plans to support my old project. As you can see last commit was around 7 years ago. The only thing working as far as I remember was custom login server.

I have plan to put the original sources of this game on separate github organization.

**Comment by mpapierski** [comment]
See librehelbreath organization

**Comment by pawelsawicz** [comment]
👍 Will do, thx!
